<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Launching siteurlhttp://way2automation.com/angularjs-protractor/banking/#/login]]>
    </line>
    <line>
      <![CDATA[Selecting customer asHermoine Granger]]>
    </line>
    <line>
      <![CDATA[Clicking on Loginbutton]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="8502" started-at="2019-10-21T14:32:10 IST" finished-at="2019-10-21T14:32:18 IST">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runners.FailureRerun@45afc369]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="8502" started-at="2019-10-21T14:32:10 IST" finished-at="2019-10-21T14:32:18 IST">
      <class name="runners.FailureRerun">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:runners.FailureRerun@45afc369]" name="setUpClass" is-config="true" duration-ms="347" started-at="2019-10-21T14:32:10 IST" finished-at="2019-10-21T14:32:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:runners.FailureRerun@45afc369]" name="feature" duration-ms="7793" started-at="2019-10-21T14:32:10 IST" description="Runs Cucumber Feature" data-provider="features" finished-at="2019-10-21T14:32:18 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Acceptance testing to validate Select Banker and Create Deposit]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: null]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: null
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at steps.BankerTransactions.the_message_on_the_screen_should_be(BankerTransactions.java:84)
at âœ½.Then the message on the screen should be "Deposit Successful"(src/test/resources/FeatureFiles/BankerTransactions.feature:24)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
            <line>
              <![CDATA[Launching siteurlhttp://way2automation.com/angularjs-protractor/banking/#/login]]>
            </line>
            <line>
              <![CDATA[Selecting customer asHermoine Granger]]>
            </line>
            <line>
              <![CDATA[Clicking on Loginbutton]]>
            </line>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:runners.FailureRerun@45afc369]" name="tearDownClass" is-config="true" duration-ms="125" started-at="2019-10-21T14:32:18 IST" finished-at="2019-10-21T14:32:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- runners.FailureRerun -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
